DOT_FILES=$HOME/.config/dot-files

# navigation

setopt AUTO_CD              # Go to folder path without usind cd.

setopt CDABLE_VARS          # Change directory to a path stored in a variable
setopt EXTENDED_GLOB        # Use extended globbing syntax.

# autocompletion
autoload -U compinit; compinit

# alias
source $DOT_FILES/aliases


# Setup Starship
eval "$(starship init zsh)"

